#include <cv.h>
#include <highgui.h>
#include <opencv2/opencv.hpp>
#include <iostream>
#include <stdio.h>
#include "opencv2/core/core.hpp"
#include "opencv2/features2d/features2d.hpp"
#include "opencv2/nonfree/features2d.hpp"
#include "opencv2/highgui/highgui.hpp"
#include "opencv2/nonfree/nonfree.hpp"
#include "Awesomium/WebCore.h"
#include <Awesomium/BitmapSurface.h>
#include <Awesomium/STLHelpers.h>
#include <sstream>
#include <opencv2/video/background_segm.hpp>
